name: farmdrive
channels: !!python/tuple
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.5.1=py35_0
- appnope=0.1.0=py35_0
- clyent=1.2.2=py35_0
- curl=7.49.0=1
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- freetype=2.5.5=1
- gdal=2.1.0=py35_0
- geos=3.5.0=0
- geotiff=1.4.1=0
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- icu=54.1=0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_1
- jpeg=8d=1
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_core=4.2.0=py35_0
- kealib=1.4.6=0
- libgdal=2.1.0=0
- libnetcdf=4.4.1=0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_0
- mistune=0.7.3=py35_1
- mkl=11.3.3=0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2i=0
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=8.1.2=py35_0
- proj4=4.9.2=0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.6.1=py35_0
- pyyaml=3.12=py35_0
- pyzmq=15.4.0=py35_0
- qt=5.6.0=0
- readline=6.2=2
- requests=2.11.1=py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.1=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- xerces-c=3.1.4=0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.9
  - awscli==1.10.66
  - babel==2.3.4
  - botocore==1.4.56
  - click==6.6
  - colorama==0.3.7
  - coverage==4.2
  - docutils==0.12
  - flake8==3.0.4
  - imagesize==0.7.1
  - ipython-genutils==0.1.0
  - jmespath==0.9.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - mccabe==0.5.2
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3
  - pyasn1==0.1.9
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - python-dotenv==0.6.0
  - rsa==3.4.2
  - s3transfer==0.1.4
  - snowballstemmer==1.2.1
  - sphinx==1.4.6
  - tqdm==4.8.4
