name: farmdrive
channels: !!python/tuple
- defaults
dependencies:
- gdal
- openssl=1.0.2i=0
- pip=8.1.2=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.9
  - awscli==1.10.66
  - babel==2.3.4
  - botocore==1.4.56
  - click==6.6
  - colorama==0.3.7
  - coverage==4.2
  - docutils==0.12
  - flake8==3.0.4
  - imagesize==0.7.1
  - jinja2==2.8
  - jmespath==0.9.0
  - markupsafe==0.23
  - mccabe==0.5.2
  - pyasn1==0.1.9
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - pygments==2.1.3
  - python-dateutil==2.5.3
  - python-dotenv==0.6.0
  - pytz==2016.6.1
  - rsa==3.4.2
  - s3transfer==0.1.4
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sphinx==1.4.6
  - tqdm
